//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBColor
    {
        public System.Guid IdColor { get; set; }
        public string code { get; set; }
        public Nullable<System.Guid> IdProduct { get; set; }
    
        public virtual TBProduct TBProduct { get; set; }
    }
}
