//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBDetail
    {
        public System.Guid IdDetails { get; set; }
        public Nullable<System.Guid> IdInvoice { get; set; }
        public Nullable<System.Guid> IdProduct { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> totalPrice { get; set; }
    
        public virtual TBInvoice TBInvoice { get; set; }
        public virtual TBProduct TBProduct { get; set; }
    }
}
