//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBInvoice()
        {
            this.TBDetails = new HashSet<TBDetail>();
        }
    
        public System.Guid IdInvoice { get; set; }
        public Nullable<System.Guid> idEmploye { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string customer { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBDetail> TBDetails { get; set; }
        public virtual TBUser TBUser { get; set; }
    }
}
