//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMsg
    {
        public System.Guid IdMsg { get; set; }
        public string Msg { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string mail { get; set; }
        public string subject { get; set; }
        public Nullable<System.Guid> IdUser { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual TBUser TBUser { get; set; }
    }
}
